---
title: "Research"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 2
    #code_folding: hide
---

## Graduate Research

January 2019-Present	**Novel Methodological Techniques for Coding Sleep States in Infancy**
	Child Development Lab at the College of Staten Island
Supervisor: Dr. Sarah Berger

December 2018-Present	**Head-mounted Eye Tracking and Infant Reaching Behavior**
	Child Development Lab at the College of Staten Island
Supervisor: Dr. Sarah Berger

September 2016-Present	**The Relation Between Physical Space and Young Children’s Play: A Cross-Cultural Examination**
Child Development Lab at the College of Staten Island
		Supervisor: Dr. Sarah Berger
		
August 2016-Present	**Learning to Solve a Novel Locomotor Problem in Infancy: Does Sleep Play a Role?**
	Child Development Lab at the College of Staten Island
Supervisor: Dr. Sarah Berger

August 2016-Present **The Role of Motor Experience on Whole-Body Exploration and Problem Solving**
	Child Development Lab at the College of Staten Island
Supervisor: Dr. Sarah Berger

## Undergraduate Research

January 2013-May 2013	**Investigating the Ability of Synesthetes to Process Meaning** 
	Millersville University
	Supervisor: Dr. Shaun Cook

January 2012-May 2013 	**The Allocation of Preferred and Nonpreferred Rewards among Collaborating Children**
	Millersville University
	Supervisor: Dr. Karena Rush

December 2011 – May 2013 	**Implementing Biofeedback and Mindfulness Training in the School System**
	Millersville University
	Supervisor: Dr. Karena Rush

February 2012 	**Using Biofeedback Training to Reduce Performance-Related Anxiety in Children** 
	Millersville University
	Supervisor: Dr. Karena Rush


October 2010-August 2012		**Preference Assessment in Infants and Toddlers** 
Millersville University
	Supervisor: Dr. Karena Rush


October 2010-May 2011		**Social Skills in Children** 
Millersville University
	Supervisor: Dr. Karena Rush
